### PR TITLE
Introduce test/mbio/mb_read_init_test.cc

### PR DESCRIPTION
**Pull request by schwehr**
Cause finding #794

### CODE REVIEW

**Comment by schwehr** [comment]
ab3d8b035049d151dba914650380c09b772cf05f attempted to fix:

```
g++ -DHAVE_CONFIG_H -I. -I../../src/mbio  -I../../third_party/googletest/include -I../../third_party/googlemock/include -I../../src -isystem    -DGTEST_HAS_PTHREAD=0 -g -O2 -MT mb_read_init_test.o -MD -MP -MF $depbase.Tpo -c -o mb_read_init_test.o mb_read_init_test.cc &&\
mv -f $depbase.Tpo $depbase.Po
In file included from mb_read_init_test.cc:6:
../../src/mbio/mb_io.h:32:10: fatal error: r7k-reader.h: No such file or directory
 #include "r7k-reader.h"
```

But that then triggered:

```
gcc -DHAVE_CONFIG_H -I. -I../../src/mbio  -g -O0 -I../../src/mbtrn/r7kr -I../../src/mbtrn/utils -I../../src/mbtrn/mframe/src -I../../src/mbtrnav/terrain-nav -I../../src/mbtrnav/gctp -I../../src/mbtrnav/newmat -I../../src/mbtrnav/qnx-utils -I../../src/mbtrnav/trnw -I../../src/mbtrnav/utils  -DHAVE_CONFIG_H  -DWITH_TESTS -DWITH_R7KR_TEST -DWITH_MST_MSTATS -DMST_STATS_EN -DWITH_PDEBUG -DWITH_MMDEBUG -D_GNU_SOURCE -DMFRAME_BUILD="`date +%Y/%m/%dT%H:%M:%S%z`" '-DFRAMES7K_VER=1.0' '-DTRNC_VER=1.0' '-DSTREAM7K_VER=1.0' '-DTBIN_VER=1.0' '-DEMU_VER=1.0' -DWITH_MBTNAV    -O2 -MT mbtrnpp.o -MD -MP -MF $depbase.Tpo -c -o mbtrnpp.o mbtrnpp.c &&\
mv -f $depbase.Tpo $depbase.Po
[SNIP]
../../src/mbtrn/mframe/src/mmdebug.h:179:68: note: in definition of macro ‘PMPRINT’
 #define PMPRINT(mod,cmsk,x) if(mmd_channel_isset(mod,cmsk))fprintf x
                                                                    ^
mbtrnpp.c: In function ‘mbtrnpp_reson7kr_input_read’:
mbtrnpp.c:3344:65: error: ‘me_errno’ undeclared (first use in this function); did you mean ‘re_errno’?
       if ((NULL!=reader && reader->state==R7KR_INITIALIZED) || (me_errno==ME_ESOCK) || (me_errno==ME_EOF)  ) {
                                                                 ^~~~~~~~
                                                                 re_errno
mbtrnpp.c:3344:65: note: each undeclared identifier is reported only once for each function it appears in
mbtrnpp.c:3344:75: error: ‘ME_ESOCK’ undeclared (first use in this function); did you mean ‘MOD_MSOCK’?
 if ((NULL!=reader && reader->state==R7KR_INITIALIZED) || (me_errno==ME_ESOCK) || (me_errno==ME_EOF)  ) {
                                                                     ^~~~~~~~
                                                                     MOD_MSOCK
mbtrnpp.c:3344:99: error: ‘ME_EOF’ undeclared (first use in this function); did you mean ‘MSG_EOK’?
 der->state==R7KR_INITIALIZED) || (me_errno==ME_ESOCK) || (me_errno==ME_EOF)  ) {
                                                                     ^~~~~~
                                                                     MSG_EOK
```

**Comment by schwehr** [comment]
This pull request didn't have a successful build, so I would have recommended against merging it yet.

**Comment by schwehr** [comment]
I am seeing a segfault.  I will try to figure out what's going wrong in the next day or two

**Comment by dwcaress** [comment]
Kurt,
I’m working on this today - the test is exposing a memory management fault.
Dave

> On Jan 6, 2020, at 6:22 AM, Kurt Schwehr <notifications@github.com> wrote:
> 
> I am seeing a segfault. I will try to figure out what's going wrong in the next day or two
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by schwehr** [comment]
It looks like I am not calling whatever is needed to setup mb_alloc_ptr in mb_mem.c.

```c
static void *mb_alloc_ptr[MB_MEMORY_HEAP_MAX];
```

Setup:

```
./autogen.sh
CFLAGS='-g -O2 -Wno-format -Wno-stringop-truncation -Wno-stringop-overflow -Wall -Wextra -Wno-sign-compare -Wno-maybe-uninitialized -Wno-format-overflow' ./configure --enable-static --disable-shared --enable-test --prefix=`pwd`/inst
make clean -j 50 && make -j 50 check

[SNIP]
/home/schwehr/src/mbsystem

libtool: link: g++ -DGTEST_HAS_PTHREAD=0 -g -O2 -m64 -o mb_time_test mb_time_test.o  ../../src/mbio/.libs/libmbio.a -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial /home/schwehr/src/mbsystem/src/bsio/.libs/libmbbsio.a /home/schwehr/src/mbsystemsrc/surf/.libs/libmbsapi.a /home/schwehr/src/mbsystemsrc/gsf/.libs/libmbgsf.a -lgmt -lpostscriptlight -lnetcdf -lhdf5_hl -lhdf5 -lsz -lz -ldl /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so /usr/lib/x86_64-linux-gnu/libproj.so ../../third_party/googletest/lib/.libs/libgtest_main.a /home/schwehr/src/mbsystemthird_party/googletest/lib/.libs/libgtest.a ../../third_party/googletest/lib/.libs/libgtest.a -lpthread -lm -pthread
make[3]: Leaving directory '/home/schwehr/src/mbsystem/test/mbio'
make  check-TESTS
make[3]: Entering directory '/home/schwehr/src/mbsystem/test/mbio'
make[4]: Entering directory '/home/schwehr/src/mbsystem/test/mbio'
PASS: mb_time_test
../../test-driver: line 107: 248391 Segmentation fault      "$@" > $log_file 2>&1
```

Debugging:

```
gdb mb_read_init_test 
GNU gdb (GDB) 8.3

(gdb) r

Running main() from src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from MbReadInitTest
[ RUN      ] MbReadInitTest.errorBadFormat
[       OK ] MbReadInitTest.errorBadFormat (1 ms)
[ RUN      ] MbReadInitTest.errorFileDoesNotExist
ERROR: invalid time
ERROR: invalid time

Program received signal SIGSEGV, Segmentation fault.
0x000055555557c041 in mb_freed (verbose=verbose@entry=0, sourcefile=sourcefile@entry=0x55555594e14c "mb_mem.c", sourceline=sourceline@entry=1120, ptr=ptr@entry=0x7ffffffff3d8, 
    error=error@entry=0x7fffffffd504) at mb_mem.c:538
538		for (int i = 0; i < n_mb_alloc; i++)
(gdb) bt
#0  0x000055555557c041 in mb_freed (verbose=verbose@entry=0, sourcefile=sourcefile@entry=0x55555594e14c "mb_mem.c", sourceline=sourceline@entry=1120, ptr=ptr@entry=0x7ffffffff3d8, 
    error=error@entry=0x7fffffffd504) at mb_mem.c:538
#1  0x000055555557e29e in mb_deall_ioarrays (verbose=verbose@entry=0, mbio_ptr=mbio_ptr@entry=0x7fffffffd508, error=error@entry=0x7fffffffd504) at mb_mem.c:1120
#2  0x00005555555674fb in mb_read_init (verbose=verbose@entry=0, file=file@entry=0x7fffffffd5a0 "/does/not/exist", format=<optimized out>, format@entry=11, pings=pings@entry=1, 
    lonflip=lonflip@entry=0, bounds=bounds@entry=0x7fffffffd580, btime_i=0x7fffffffd540, etime_i=0x7fffffffd560, speedmin=speedmin@entry=0, timegap=timegap@entry=0, mbio_ptr=0x7fffffffd508, 
    btime_d=0x7fffffffd510, etime_d=0x7fffffffd518, beams_bath=0x7fffffffd4f8, beams_amp=0x7fffffffd4fc, pixels_ss=0x7fffffffd500, error=0x7fffffffd504) at mb_read_init.c:295
#3  0x0000555555565d47 in (anonymous namespace)::MbReadInitTest_errorFileDoesNotExist_Test::TestBody (this=<optimized out>) at mb_read_init_test.cc:60
#4  0x000055555594880a in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x5555559d4b0d "the test body", method=<optimized out>, 
    object=0x555555b4d8a0) at ./src/gtest.cc:2418
#5  testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x555555b4d8a0, method=<optimized out>, 
    location=location@entry=0x5555559d4b0d "the test body") at ./src/gtest.cc:2473
#6  0x000055555593bd96 in testing::Test::Run (this=this@entry=0x555555b4d8a0) at ./src/gtest.cc:2512
#7  0x000055555593c1ba in testing::Test::Run (this=0x555555b4d8a0) at ./src/gtest.cc:2688
#8  testing::TestInfo::Run (this=0x555555b6d700) at ./src/gtest.cc:2688
#9  0x000055555593c34b in testing::TestInfo::Run (this=<optimized out>) at ./src/gtest.cc:2662
#10 testing::TestSuite::Run (this=0x555555b6d630) at ./src/gtest.cc:2818
#11 0x0000555555940643 in testing::TestSuite::Run (this=<optimized out>) at ./src/gtest.cc:2798
#12 testing::internal::UnitTestImpl::RunAllTests (this=0x555555b6d3a0) at ./src/gtest.cc:5276
#13 0x0000555555948cca in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (
    location=0x5555559d5b58 "auxiliary test code (environments or event listeners)", method=<optimized out>, object=0x555555b6d3a0) at ./src/gtest.cc:2418
#14 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x555555b6d3a0, method=<optimized out>, 
    location=location@entry=0x5555559d5b58 "auxiliary test code (environments or event listeners)") at ./src/gtest.cc:2473
#15 0x000055555593bedd in testing::UnitTest::Run (this=0x555555b33860 <testing::UnitTest::GetInstance()::instance>) at ./include/gtest/gtest.h:1392
#16 0x000055555556531b in RUN_ALL_TESTS () at ./include/gtest/gtest.h:2448
#17 main (argc=<optimized out>, argv=0x7fffffffdd18) at src/gtest_main.cc:45
(gdb) print i
$1 = 0
```

**Comment by schwehr** [comment]
ASAN says there is trouble here:  (this is a bazel build...)

```
==1711==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f952cf36be0 at pc 0x7f9537cb66e9 bp 0x7ffd93bb4c80 sp 0x7ffd93bb4c78
READ of size 8 at 0x7f952cf36be0 thread T0
    #0 0x7f9537cb66e8 in mb_freed third_party/mbsystem/mbio/mb_mem.c:539:26
    #1 0x7f9537cbad51 in mb_deall_ioarrays third_party/mbsystem/mbio/mb_mem.c:1115:12
    #2 0x7f9537d1cad2 in mb_read_init third_party/mbsystem/mbio/mb_read_init.c:295:12
    #3 0x7f9538b5acc7 in (anonymous namespace)::MbReadInitTest_doesNotExist_Test::TestBody() third_party/mbsystem/test/mbio/mb_read_init_test.cc:53:3
    #4 0x7f9532ac4086 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2555:10
    #5 0x7f9532aa8c78 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2610:12
    #6 0x7f9532a8d784 in testing::Test::Run() third_party/googletest/googletest/src/gtest.cc:2630:5
    #7 0x7f9532a8e1f1 in testing::TestInfo::Run() third_party/googletest/googletest/src/gtest.cc:2807:11
    #8 0x7f9532a8e911 in testing::TestSuite::Run() third_party/googletest/googletest/src/gtest.cc:2939:28
    #9 0x7f9532a9cc92 in testing::internal::UnitTestImpl::RunAllTests() third_party/googletest/googletest/src/gtest.cc:5480:44
    #10 0x7f9532acb476 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2555:10
    #11 0x7f9532aab408 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2610:12
    #12 0x7f9532a9c62b in testing::UnitTest::Run() third_party/googletest/googletest/src/gtest.cc:5067:10
    #13 0x55561fa72270 in RUN_ALL_TESTS() third_party/googletest/googletest/include/gtest/gtest.h:2475:46
    #14 0x55561fa71bd6 in main testing/base/internal/gunit_main.cc:77:10
    #15 0x7f95302c2bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
    #16 0x55561f9c10c8 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108

Address 0x7f952cf36be0 is located in stack of thread T0 at offset 992 in frame
    #0 0x7f9530ba469f in absl::str_format_internal::FormatUntyped(absl::str_format_internal::FormatRawSinkImpl, absl::str_format_internal::UntypedFormatSpecImpl, absl::Span<absl::str_format_internal::FormatArgImpl const>) third_party/absl/strings/internal/str_format/bind.cc:186

  This frame has 2 object(s):
    [32, 1088) 'sink' (line 187) <== Memory access at offset 992 is inside this variable
    [1216, 1224) 'agg.tmp3'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return third_party/mbsystem/mbio/mb_mem.c:539:26 in mb_freed
Shadow bytes around the buggy address:
  0x0ff3259ded20: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259ded30: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259ded40: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259ded50: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259ded60: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x0ff3259ded70: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5
  0x0ff3259ded80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259ded90: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259deda0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259dedb0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff3259dedc0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```

**Comment by dwcaress** [comment]
Kurt,

Is it still there after my commits tonight?

Dave


> On Jan 6, 2020, at 9:59 PM, Kurt Schwehr <notifications@github.com> wrote:
> 
> ASAN says there is trouble here: (this is a bazel build...)
> 
> ==1711==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f952cf36be0 at pc 0x7f9537cb66e9 bp 0x7ffd93bb4c80 sp 0x7ffd93bb4c78
> READ of size 8 at 0x7f952cf36be0 thread T0
>     #0 0x7f9537cb66e8 in mb_freed third_party/mbsystem/mbio/mb_mem.c:539:26
>     #1 0x7f9537cbad51 in mb_deall_ioarrays third_party/mbsystem/mbio/mb_mem.c:1115:12
>     #2 0x7f9537d1cad2 in mb_read_init third_party/mbsystem/mbio/mb_read_init.c:295:12
>     #3 0x7f9538b5acc7 in (anonymous namespace)::MbReadInitTest_doesNotExist_Test::TestBody() third_party/mbsystem/test/mbio/mb_read_init_test.cc:53:3
>     #4 0x7f9532ac4086 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2555:10
>     #5 0x7f9532aa8c78 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2610:12
>     #6 0x7f9532a8d784 in testing::Test::Run() third_party/googletest/googletest/src/gtest.cc:2630:5
>     #7 0x7f9532a8e1f1 in testing::TestInfo::Run() third_party/googletest/googletest/src/gtest.cc:2807:11
>     #8 0x7f9532a8e911 in testing::TestSuite::Run() third_party/googletest/googletest/src/gtest.cc:2939:28
>     #9 0x7f9532a9cc92 in testing::internal::UnitTestImpl::RunAllTests() third_party/googletest/googletest/src/gtest.cc:5480:44
>     #10 0x7f9532acb476 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2555:10
>     #11 0x7f9532aab408 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) third_party/googletest/googletest/src/gtest.cc:2610:12
>     #12 0x7f9532a9c62b in testing::UnitTest::Run() third_party/googletest/googletest/src/gtest.cc:5067:10
>     #13 0x55561fa72270 in RUN_ALL_TESTS() third_party/googletest/googletest/include/gtest/gtest.h:2475:46
>     #14 0x55561fa71bd6 in main testing/base/internal/gunit_main.cc:77:10
>     #15 0x7f95302c2bbc in __libc_start_main (/usr/grte/v4/lib64/libc.so.6+0x38bbc)
>     #16 0x55561f9c10c8 in _start /usr/grte/v4/debug-src/src/csu/../sysdeps/x86_64/start.S:108
> 
> Address 0x7f952cf36be0 is located in stack of thread T0 at offset 992 in frame
>     #0 0x7f9530ba469f in absl::str_format_internal::FormatUntyped(absl::str_format_internal::FormatRawSinkImpl, absl::str_format_internal::UntypedFormatSpecImpl, absl::Span<absl::str_format_internal::FormatArgImpl const>) third_party/absl/strings/internal/str_format/bind.cc:186
> 
>   This frame has 2 object(s):
>     [32, 1088) 'sink' (line 187) <== Memory access at offset 992 is inside this variable
>     [1216, 1224) 'agg.tmp3'
> HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
>       (longjmp and C++ exceptions *are* supported)
> SUMMARY: AddressSanitizer: stack-use-after-return third_party/mbsystem/mbio/mb_mem.c:539:26 in mb_freed
> Shadow bytes around the buggy address:
>   0x0ff3259ded20: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259ded30: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259ded40: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259ded50: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259ded60: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
> =>0x0ff3259ded70: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5
>   0x0ff3259ded80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259ded90: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259deda0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259dedb0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
>   0x0ff3259dedc0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07 
>   Heap left redzone:       fa
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
>   Shadow gap:              cc
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by schwehr** [comment]
Some notes/code review while checking:

I will try to put these comments on the relevant commits when I get time.

- Is looks like the overall fix boils down to adding `MB_ERROR_BAD_TIME`, yes?
- The commit messages don't tell me much about what you were thinking in each change, so I'm going through the entire diff from 9ceaa5a7f48d034548ede36de852f9cb65aa8fa3 to head
- Why remove data files if there is no valid data.  That's still checking the format right?
- (looking at mb7kpreprocess.cc) Initializing all the `char foo[MB_PATH_MAXLINE];` with `= ""` is generally great, but we should try to create the variable and set it to it's final value whenever possible and then make it `const`
- Why is there now mb_default_defaults?  And why is it exposed in mb_define.h?
- src/mbio/mb_read_init.c: mem_error is never checked.  Should it or the return of mb_freed be checked?
- Typo: mb_time.c: `made.These`
- In general, most people prefer using a semantic name rather than an index.  Then there is no need for comments.  Try to prefer code that doesn't need comments.  e.g. `const int year = time_i[0];` should be used rather than `time_i[0] < 1930 || time_i[0] > 3000       // year`.  This is still pretty rough to understand:  `((time_i[0] % 4 == 0 && time_i[0] % 100 != 0) || time_i[0] % 400 == 0) && (time_i[1] > 2)` if you end up looking at the code while debugging something else.   I didn't push my changes like that more as I was planning to factor out printing time_i to be a function.  And maybe someday, time_i really should become a struct so the indices go away altogether.
- Don't put in redundant comments.  e.g. `/* return success */\n return (status);` . This comment is just extra work for the reader.
- I can't tell if anything changed in `mb_get_date`.  And same for all the other functions in that file.
- mbinfo_test.py: Disable python tests without commenting them out using `@unittest.skip`.  See 275602428dbe42fdf373e693e593bcc158c6cd1b
- `// t should be set to zero` mentioned in the test.  That needs to be called out in comment before `mb_get_time()` in `mb_time.c`.
- `mbinfo_generate.cmd` needs explanation
- I don't like the inf files for testing as white space changes can bring the house down.  e.g. bad trailing whitespace here: `Attributes:           SeaBeam 2100, bathymetry and amplitude,  `

I will try the code in a few minutes.

**Comment by schwehr** [comment]
Passes asan and msan.

**Pull request merged**
